### ISSUE TITLE
No fastqc Module on Gadi

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Fastq-to-BAM#11]
fastqc_run_parallel.pbs has `module load fastqc/0.11.7`

```
$ module load fastqc/0.11.7
ERROR: Unable to locate a modulefile for 'fastqc/0.11.7'
```

Of course, it is in apps folder. But, the script in its current form doesn't work.

**Comment by georgiesamaha** [comment]
Module file is now available on Gadi at /apps/Modules/modulefiles/fastqc
