### ISSUE TITLE
align_make_input.sh lib_diff is Initialised Empty and Never Set Otherwise

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Fastq-to-BAM#12]
On line 51, `lib_diff=''` is declared, it is never set to anything else and is checked on line 64 `if [ "$lib_diff" ]`.

**Comment by calizilla** [comment]
Thanks Dario. This was a relic from OSCC cohort which had 2 libraries per sample, the script and config was customised to address this. The $lib_diff variable has now been removed.
