### ISSUE TITLE
Dict Value Assignment Missing

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Fastq-to-BAM#13]
https://github.com/Sydney-Informatics-Hub/Fastq-to-BAM/blob/bb70063468ce127174036dff40f9667506f6ebd6/bqsr_merge_make_input.sh#L25

Empty variable declaration, so it stalls at the awk and sed command below and never returns control to the user. Perhaps it needs documenting as a required setting by the end user, as well as the line `ref=../Reference/canFam4.fasta` in the merging worker script.

**Comment by georgiesamaha** [comment]
Sorry for the delay Dario, the create_project.sh script has been updated and these issues are addressed in the new version. The script now also allows for autofilling of lstorage with /gdata or /scratch paths.
