### ISSUE TITLE
samblaster Path Hard-Coded to Inaccessible Path

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Fastq-to-BAM#17]
I noticed all error logs had samblaster errors, such as:

```
$ cat Logs/Dedup_sort_error_capture/OSCC_45-CC_M.err
Corrupted or missing BAM
Error in samblaster log
```

I think the reason is in `dedup_sort.sh`.

```
# Does not like being in run_parallel script
samblaster=/scratch/er01/apps/samblaster/0.1.24/samblaster
```

The path is not accessible to end-users.

```
$ ls /scratch/er01/apps/samblaster/0.1.24/samblaster
ls: cannot access '/scratch/er01/apps/samblaster/0.1.24/samblaster': No such file or directory
```

This crucial edit which must be done by end-user should be stated in `README.md`.

**Comment by calizilla** [comment]
I removed the offending relic line from the script. The samblaster module (global app) is loaded within the driver script dedup_sort_run_parallel.pbs, so there is no need for the user to update path to samblaster within the dedup_sort.sh task script.
