### ISSUE TITLE
BQSR Recalibration Make Input Only Processes Normal Sample Files

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Fastq-to-BAM#18]
Shouldn't all BAM files be recalibrated? It looks like a bad copy and paste from the germline variant pipeline.

```
# Collect sample IDs from samples.config
# Only collect IDs for germline variant calling (labids ending in -B or -N)
while read -r sampleid labid seq_center library; do
        if [[ ! ${sampleid} =~ ^#.*$ && ! ${labid} =~ -T.*$ && ! ${labid} =~ -P.*$ && ! ${labid} =~ -M.*$ ]]; then
```

Therefore, the nested tumour code segement will never be executed because any disease samples were previously excluded.

```
else
  samples_t+=("${labid}")
  group_input=${t_input}
fi
```

**Comment by calliza** [comment]
Thanks for spotting this Dario, all fixed.

**Comment by calizilla** [comment]
Thanks for pointing out this Dario, all fixed now.
