### ISSUE TITLE
Hard-Coded Dependencies on er01 Scratch

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Fastq-to-BAM#2]
A number of scripts depend on software or other resources located in `/scratch/er01/`. For example, `split_fastq.sh` has

```
fastp=/scratch/er01/apps/fastp/0.20.0/fastp
```

The folder no longer exists on Gadi.

**Comment by calliza** [comment]
Hi Dario, 

We are aware of this. For software that are not installed globally on Gadi, users will need to install the sotware themselves and update the paths or module commands as required. 

The fastp executable is reference in the script like this:

`fastp=/scratch/<project>/apps/fastp/0.20.0/fastp #or replace with module load if appropriate`

This is just a placeholder for the user to indicate the path to their fastp executable or add a module load command if they have set up the software to be compatible with module commands. 

Kind regards,
Cali

**Comment by DarioS** [comment]
Ah, nevermind. I was using an older version of the script which didn't have the placeholder but persisted in Gadi since last year.
