### ISSUE TITLE
Where to download nci-parallel/1.0.0?

### ISSUE THREAD

**Issue by tkcaccia** [Sydney-Informatics-Hub/Fastq-to-BAM#20]
Could you please indicate where to download the nci-parallel software, please?

**Comment by georgiesamaha** [comment]
Hi @tkcaccia, 

This workflow has been specifically designed for NCI's Gadi HPC and [nci-parallel](https://opus.nci.org.au/display/Help/nci-parallel) is specially developed for (and only available at) NCI's Gadi HPC. If you are interested in porting these scripts to another infrastructure, you may be able to replace nci-parallel with [GNU Parallel](https://www.gnu.org/software/parallel/). 

Good luck!
