### ISSUE TITLE
bqsr_recal.sh has Empty ref Variable

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Fastq-to-BAM#25]
Instructions don't say to fill in `ref` before executing PBS driver script (only `$dbsnp` mentioned for non-human in make input script).

```
ref=
thousandG_indels=../Reference/Known_vars/Homo_sapiens_assembly38.known_indels.vcf
gold_standard_indels=../Reference/Known_vars/Mills_and_1000G_gold_standard.indels.hg38.vcf
dbsnp=../Reference/Known_vars/Homo_sapiens_assembly38.dbsnp138.vcf
```

**Comment by calizilla** [comment]
Hi Dario, 
The `ref` variable is automatically filled when you run and enter the required inputs to the `create_project.sh` setup script. This is why updating this variable is not within the README for `bqsr_recal.sh`. 
Kind regards
Cali
