### ISSUE TITLE
Minimum Information about Whole-genome Sequencing

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Fastq-to-BAM#27]
Some journals now require detailed metrics, e.g. [International Journal of Cancer](https://onlinelibrary.wiley.com/page/journal/10970215/homepage/forauthors.html). This pipeline does not calculate most metrics.

![image](https://github.com/user-attachments/assets/528fc08c-baf5-4f8c-a384-3b6b6468fa20)

**Comment by calizilla** [comment]
Hi Dario, the pipeline doesn't claim to calculate these metrics and there are many external tools that can be run to obtain the details this journal is asking for. For example you could try this workflow, to be run after the BAM creation: https://github.com/Sydney-Informatics-Hub/bamQC-nf 

We are not actively updating this pipeline as newer tools bwa-mem2, DeepVariant and GLNexus provide better efficiency and sensitivity than the GATK pipeline.

**Comment by DarioS** [comment]
Indeed, bamQC-nf calculates all five columns of the template table. Thanks for alerting me to it.
