### ISSUE TITLE
Split FASTQ Make Input Loses Input Files

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Fastq-to-BAM#6]
It coverts the result into an array by `fqpairs=($fqpairs)` but then it treats the variable not like an array but an ordinary variable `printf "${fqpairs}\n" >> $inputs`, only printing out the first array value into the file. There is no need to convert it into an array. It could be simply written as `printf '%s\n' $fqpairs > $inputs`.

Another tweak could be replacing `ls` by `find`, in case the data has been supplied in a complicated set of nested directories extracted from a TAR file of an entire batch of samples. `find` is recursive by default, unlike `ls`.

```bash
$ find ../Fastq -name ${sample}*f*q.gz
Fastq/SAT9315/SAT9315-Run1/SAT9362A1/OSCC_38_N_S10_L002_R1_001.fastq.gz
Fastq/SAT9315/SAT9315-Run1/SAT9362A1/OSCC_38_N_S10_L002_R2_001.fastq.gz
Fastq/SAT9315/SAT9315-Run1/SAT9362A1/OSCC_38_N_S10_L003_R2_001.fastq.gz
Fastq/SAT9315/SAT9315-Run1/SAT9362A1/OSCC_38_N_S10_L004_R1_001.fastq.gz
Fastq/SAT9315/SAT9315-Run1/SAT9362A1/OSCC_38_N_S10_L004_R2_001.fastq.gz
Fastq/SAT9315/SAT9315-Run1/SAT9362A1/OSCC_38_N_S10_L001_R1_001.fastq.gz
Fastq/SAT9315/SAT9315-Run1/SAT9362A1/OSCC_38_N_S10_L003_R1_001.fastq.gz
Fastq/SAT9315/SAT9315-Run1/SAT9362A1/OSCC_38_N_S10_L001_R2_001.fastq.gz
Fastq/SAT9315/SAT9315-Run2/SAT9362/SAT9362A1/OSCC_38_N_S17_L001_R1_001.fastq.gz
Fastq/SAT9315/SAT9315-Run2/SAT9362/SAT9362A1/OSCC_38_N_S17_L002_R2_001.fastq.gz
Fastq/SAT9315/SAT9315-Run2/SAT9362/SAT9362A1/OSCC_38_N_S17_L001_R2_001.fastq.gz
Fastq/SAT9315/SAT9315-Run2/SAT9362/SAT9362A1/OSCC_38_N_S17_L002_R1_001.fastq.gz
```

This batch is by Ramaciotti Centre, UNSW.

**Comment by georgiesamaha** [comment]
Thanks for letting up know about this problem Dario, I've fixed the script and replaced ls -l with find as per your suggestion :)
