### ISSUE TITLE
Broken Path to Fixed NCI Parallel

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Fastq-to-BAM#7]
The file direcory previously storing it `/scratch/public/bjm900/` was deleted. `module load nci-parallel/1.0.0a` is the new way,

**Comment by georgiesamaha** [comment]
Thanks for letting us know Dario! I have fixed the nci-parallel path within the mpirun command and included module load nci-parallel/1.0.0a and module load openmpi/4.1.0 in all run_parallel scripts.
